#pragma config(Motor,  port1,           rightForwardMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontSideMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           gunMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           miniWheelMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           lowerPlatformMotors, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rearSideMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          leftForwardMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Dual Joystick Control with 4 Motors -                               *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing both right-side motors (ports 2 and 3) in the "Motors and Sensors Setup" is       *|
|*        needed with the "VEX Tumbler" model, but may not be needed for all robot configurations.    *|
|*    2)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    3)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]                [Type]                [Description]                   *|
|*    Motor Port 2        frontRightMotor       VEX 3-wire module     Right side motor                *|
|*    Motor Port 3        backRightMotor        VEX 3-wire module     Right side motor                *|
|*    Motor Port 4        frontLefttMotor       VEX 3-wire module     Left side motor                 *|
|*    Motor Port 5        backLeftMotor         VEX 3-wire module     Left side motor
|*		motor port 6        arm motor							VEX 3-wire module			arm motor
|*		motor port 7				claw motor						VEX 3-wire module			claw motor
|*		motor port 8				gun motor							VEX 3-wire module			gun motor
|*    motor port 9				lowerPlatformMotor		VEX 3-Wire module			lowerPlatformMotor
|*	  motor port 10       upperplatformMotor
\*----------------------------------------------------------------------------------------------------*/

#define DEADBAND 10

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  while(1==1)
  {
    //Left Joystick Y-axis controls Left Forward Motor
  	if(abs(vexRT[Ch3]) > DEADBAND) // If the left joystick is greater than or less than the threshold:
		{
			motor[leftForwardMotor] = (vexRT[Ch3])/2; // Left Joystick Y value / 2.
		}
		else // If the left joystick is within the threshold:
		{
			motor[leftForwardMotor] = 0; // Stop the left motor (cancel noise)
		}

    //Right Joystick Y-axis controls Right Forward Motor
  	if(abs(vexRT[Ch2]) > DEADBAND) // If the Right joystick is greater than or less than the threshold:
		{
			motor[rightForwardMotor] = (vexRT[Ch2])/2; // Right Joystick Y value / 2.
		}
		else // If the Right joystick is within the threshold:
		{
			motor[rightForwardMotor] = 0; // Stop the left motor (cancel noise)
		}

	  //Right Joystick X-axis controls Right Forward Motor
  	if(abs(vexRT[Ch1]) > DEADBAND) // If the Right joystick is greater than or less than the threshold:
		{
			motor[frontSideMotor] = (vexRT[Ch1])/2; // Right Joystick Y value / 2.
		}
		else // If the Right joystick is within the threshold:
		{
			motor[frontSideMotor] = 0; // Stop the left motor (cancel noise)
		}

	  //Right Joystick X-axis controls Right Forward Motor
  	if(abs(vexRT[Ch4]) > DEADBAND) // If the Right joystick is greater than or less than the threshold:
		{
			motor[rearSideMotor] = (vexRT[Ch4])/2; // Right Joystick Y value / 2.
		}
		else // If the Right joystick is within the threshold:
		{
			motor[rearSideMotor] = 0; // Stop the left motor (cancel noise)
		}

    // Check if button to lift arm is pressed
    if(vexRT[Btn5U]==1)
    {
    	motor[armMotor]=127;
    }
    // Check if button to drop arm is pressed
    else if(vexRT[Btn5D]==1)
    {
      motor[armMotor]=-127;
    }
    // Neither arm button is pressed
    else
    {
    	motor[armMotor]=0;
    }

    // Check if button to turn the claw arm is pressed
    if(vexRT[Btn6U]==1)
    {
    	motor[clawMotor]=127;
    }
    // Check if button to turn the claw the opposite direction is pressed
    else if(vexRT[Btn6D]==1)
    {
      motor[clawMotor]=-127;
    }
    // Neither arm button is pressed
    else
    {
    	motor[clawMotor]=0;
    }

    // Add Code to shoot gun
    // if 7r is pressed then draw back trigger
    if(vexRT[Btn7R]==1)
    {
  		motor[gunMotor]=-127;
		}
  	//if released shoots ball
			else
		{
			motor[gunMotor]=0;
		}

		//press 8u to raise platform
		if(vexRT[Btn8U]==1)
		{
			motor[lowerPlatformMotors]=127;
		}
		//if you are pressing 8d lower the platform
		else if(vexRT[Btn8D]==1)
		{
			motor[lowerPlatformMotors]=-127;
		}
		//if no pressing 8u stop
		else
		{
			motor[lowerPlatformMotors]=0;
		}

		// if pressing 7u move motor forward
		if(vexRT[Btn7U]==1)
		{
			motor[miniWheelMotor]=127;
		}
		//if you are pressing 7D lower the platform
		else if(vexRT[Btn7D]==1)
		{
			motor[miniWheelMotor]=-127;
		}
		//if no pressing 7 button stop
		else
		{
			motor[miniWheelMotor]=0;
		}
	}// end of while loop;
}// end of program


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
